### ISSUE TITLE
Code for the project

### ISSUE THREAD

**Issue by Malsententia** [charlie-x/kbd_hook#1]
Hello. I found this through the hackaday post, and I'm facing a similar situation with similar needs (I'm aiming to filter an old but good set USB foot pedals). Is there a chance the code mentioned on the article could be committed? Hoping to avoid reinventing the wheel.

Thanks,
Mal

**Comment by charlie-x** [comment]
i'll see if i can find it

**Comment by Malsententia** [comment]
Awesome! Thanks a ton!
